Fix samsungtv to abort when ATTR_UPNP_MANUFACTURER is missing
Fixes
```
2022-09-20 08:47:23.807 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/Users/bdraco/home-assistant/homeassistant/data_entry_flow.py", line 225, in async_init
    flow, result = await task
  File "/Users/bdraco/home-assistant/homeassistant/data_entry_flow.py", line 252, in _async_init
    result = await self._async_handle_step(flow, flow.init_step, data, init_done)
  File "/Users/bdraco/home-assistant/homeassistant/data_entry_flow.py", line 367, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/Users/bdraco/home-assistant/homeassistant/components/samsungtv/config_flow.py", line 461, in async_step_ssdp
    self._manufacturer = discovery_info.upnp[ssdp.ATTR_UPNP_MANUFACTURER]
KeyError: manufacturer

```