Fix missing services with esp32 proxies
```
aiohomekit.controller.ble.bleak.BleakServiceMissing: VOCOlinc-VS1-1857C6: Service 00000055-0000-1000-8000-0026BB765291 not found, available services: [00001800-0000-1000-8000-00805f9b34fb, 00001801-0000-1000-8000-00805f9b34fb, 0000003e-0000-1000-8000-0026bb765291, 000000a2-0000-1000-8000-0026bb765291, 00001530-1212-efde-1523-785feabcd123, 00000080-0000-1000-8000-0026bb765291]
switchbot.devices.device.CharacteristicMissingError: cba20003-224d-11e6-9fb8-0002a5d5c51b
```

We need to be able to clear the gatt services cache when we detect service
resolution went wrong on the esp32. Since we cannot fix the BLE stack on
the ESP32, we need to clear the cache and try again