Fix WiZ bulb being offline if kelvin limits cannot be obtained
- Setup is now retried later in case the wifi was
  unstable for a moment during setup

Requires https://github.com/sbidy/pywizlight/pull/121

Changelog: https://github.com/sbidy/pywizlight/compare/v0.5.5...v0.5.6

Fixes
```
2022-02-10 18:07:19 ERROR (MainThread) [homeassistant.components.light] Error while setting up wiz platform for light
Traceback (most recent call last):
  File "/Users/bdraco/home-assistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/Users/bdraco/home-assistant/homeassistant/components/wiz/light.py", line 69, in async_setup_entry
    async_add_entities([WizBulbEntity(wiz_data, entry.title)])
  File "/Users/bdraco/home-assistant/homeassistant/components/wiz/light.py", line 94, in __init__
    bulb_type.kelvin_range.max
AttributeError: NoneType object has no attribute max
```