fixed receiver.support_sound_mode being 'None'
fixed receiver.support_sound_mode being 'None' if receiver is of type avr.
The async rewrite of the denonavr components requires an update command for a reveicer of type avr so the fixed support_sound_mode is actually set.
Fixes the following error:

2021-05-11 01:31:51 ERROR (MainThread) [homeassistant.components.media_player] Error while setting up denonavr platform for media_player
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 231, in _async_setup_platform
await asyncio.shield(task)
File "/usr/src/homeassistant/homeassistant/components/denonavr/media_player.py", line 104, in async_setup_entry
DenonDevice(
File "/usr/src/homeassistant/homeassistant/components/denonavr/media_player.py", line 153, in __init__
self._supported_features_base |= (
TypeError: unsupported operand type(s) for |=: 'int' and 'NoneType'
2021-05-11 01:31:51 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event system_log_event[L]: name=homeassistant.components.media_player, message=['Error while setting up denonavr platform for media_player'], level=ERROR, source=['components/denonavr/media_player.py', 153], timestamp=1620689511.5018213, exception=Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 231, in _async_setup_platform
await asyncio.shield(task)
File "/usr/src/homeassistant/homeassistant/components/denonavr/media_player.py", line 104, in async_setup_entry
DenonDevice(
File "/usr/src/homeassistant/homeassistant/components/denonavr/media_player.py", line 153, in __init__
self._supported_features_base |= (
TypeError: unsupported operand type(s) for |=: 'int' and 'NoneType'