Starlink's energy consumption & usage cumulation fix (#135889)
* refactor: history_stats result indexing

* fix: Energy consumption & Usage cumulation

* fix: typo

* fix: mypy error: Call to untyped function

* refactor: Use generic tuple instead of typing's Tuple

* fix: tuple

* fix: just syntax test

* fix: AttributeError: 'NoneType' object has no attribute 'usage'

* refactor: Return type

* refactor: Merge into single method

* refactor: Complex unpack test