Avoid duplicated config entry deletion
When removing a device from Matter, a stack trace is currently printed:

```
2024-06-28 08:42:22.806 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140539986712976] Error handling message: Unknown error (unknown_error) test from 127.0.0.1 (Mozilla/5.0 (X11; Linux x86_64; rv:127.0) Gecko/20100101 Firefox/127.0)
Traceback (most recent call last):
  File "/home/sag/projects/home-assistant/core/homeassistant/components/websocket_api/decorators.py", line 28, in _handle_async_response
    await func(hass, connection, msg)
  File "/home/sag/projects/home-assistant/core/homeassistant/components/config/device_registry.py", line 141, in websocket_remove_config_entry_from_device
    entry = registry.async_update_device(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sag/projects/home-assistant/core/homeassistant/helpers/device_registry.py", line 857, in async_update_device
    old = self.devices[device_id]
          ~~~~~~~~~~~~^^^^^^^^^^^
  File "/usr/lib/python3.12/collections/__init__.py", line 1135, in __getitem__
    raise KeyError(key)
KeyError: 'c4e4dbda8bca500ea1475539b5e17a52'
```

The reason is that the current Matter implementation automatically
deletes a config entry when the server notifies us of a device removal.
At the same time, async_remove_config_entry_device() which gets called
when a user deletes from within Home Assistant Core, also takes care of
deleting the config entry. This second deletion then leads to the above
stack trace.

Fix this by preventing deletion on Matter server events, if the deletion
was Home Assistant Core triggered initially.