Fix zwave_js failing to download diagnostics
I get an error here when downloading diagnostics for my ZEN52 dual relays:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 67, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 227, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 235, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 146, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/diagnostics/__init__.py", line 265, in get
    data = await info.device_diagnostics(hass, config_entry, device)
  File "/usr/src/homeassistant/homeassistant/components/zwave_js/diagnostics.py", line 136, in async_get_device_diagnostics
    entities = get_device_entities(hass, node, device)
  File "/usr/src/homeassistant/homeassistant/components/zwave_js/diagnostics.py", line 69, in get_device_entities
    if (value_id := get_value_id_from_unique_id(entry.unique_id)) is None:
  File "/usr/src/homeassistant/homeassistant/components/zwave_js/helpers.py", line 104, in get_value_id_from_unique_id
    if "-" in (value_id := split_unique_id[1]):
IndexError: list index out of range
```