Fix exception in home_connect.light
The line above the fixed condition might set brightness to an empty
dict if self.device.appliance.status doesn't have a brightness key.
This result in the following exception being raised and shown in
the logs:

2023-01-19 06:32:03.146 ERROR (MainThread) [homeassistant.components.light] home_connect: Error on device update!
Traceback (most recent call last):
  File "/opt/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/entity_platform.py", line 503, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/opt/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/entity.py", line 729, in async_device_update
    await task
  File "/opt/homeassistant/lib/python3.9/site-packages/homeassistant/components/home_connect/light.py", line 200, in async_update
    self._brightness = ceil((brightness.get(ATTR_VALUE) - 10) * 255 / 90)
TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'