Update to current on dev machine
Currently broken, with this error on start up:
ERROR:homeassistant.helpers.entity:Update for light.living_room fails
Traceback (most recent call last):
  File "/srv/homeassist/lib/python3.5/site-packages/homeassistant/helpers/entity.py", line 204, in async_update_ha_state
    yield from self.async_device_update()
  File "/srv/homeassist/lib/python3.5/site-packages/homeassistant/helpers/entity.py", line 309, in async_device_update
    yield from self.hass.async_add_job(self.update)
  File "/usr/lib/python3.5/asyncio/futures.py", line 380, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 304, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/srv/homeassist/lib/python3.5/site-packages/homeassistant/components/light/wemo.py", line 207, in update
    self._update(force_update=True)
  File "/srv/homeassist/lib/python3.5/site-packages/homeassistant/components/light/wemo.py", line 213, in _update
    self._brightness = self.get_brightness(force_update)
TypeError: 'int' object is not callable

I believe I am on the right track as far as subscription updates for brightness though, as it is trying to grab the brightness on startup