Remove pytest-xdist from tox now that it's in requirements_test.txt
Causes
ERROR: Double requirement given: pytest-xdist==1.32.0 (from -r .../requirements_test.txt (line 20)) (already in pytest-xdist, name='pytest-xdist')