Suppress mypy checks for incorrect typing in overkiz
This was causing all full CI runs to fail
`Error: homeassistant/components/overkiz/executor.py:122: error: "List[Dict[str, Any]]" has no attribute "get" [attr-defined]`

- action_group is typed as a list, which doesn't have a get()