lacrosse: Correctly close on homeassistant stop
Since lacrosse.close() takes no arguments, but was directly added as a
listener to EVENT_HOMEASSISTANT_STOP, the following occured on shutdown:

Traceback (most recent call last):
  File "/usr/lib/python/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
TypeError: close() takes 1 positional argument but 2 were given