mqtt_eventstream does not work due to "yield from"
When running with `PYTHONASYNCIODEBUG=1` the following error is shown:

```python
homeassistant/components/mqtt_eventstream.py:107: RuntimeWarning: coroutine 'async_subscribe' was never awaited
  yield from mqtt.async_subscribe(sub_topic, _event_receiver)

Error during setup of component mqtt_eventstream
Traceback (most recent call last):
  File "homeassistant/setup.py", line 145, in _async_setup_component
    hass, processed_config)
  File "asyncio/coroutines.py", line 110, in __next__
    return self.gen.send(None)
  File "homeassistant/components/mqtt_eventstream.py", line 107, in async_setup
    yield from mqtt.async_subscribe(sub_topic, _event_receiver)
TypeError: cannot 'yield from' a coroutine object in a non-coroutine generator
```