Fix HKC exceptions during BLE startup not being caught
Noticed this while doing some testing with an esp32 proxy

Fixes
```
2022-10-23 22:10:52.625 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved:   File "/Users/bdraco/home-assistant/venv/bin/hass", line 33, in <module>
    sys.exit(load_entry_point(homeassistant, console_scripts, hass)())
  File "/Users/bdraco/home-assistant/homeassistant/__main__.py", line 191, in main
    exit_code = runner.run(runtime_conf)
  File "/Users/bdraco/home-assistant/homeassistant/runner.py", line 119, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 600, in run_forever
    self._run_once()
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 1888, in _run_once
    handle._run()
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/bdraco/home-assistant/homeassistant/core.py", line 1050, in _onetime_listener
    self._hass.async_run_job(listener, event)
  File "/Users/bdraco/home-assistant/homeassistant/core.py", line 621, in async_run_job
    return self.async_run_hass_job(HassJob(target), *args)
  File "/Users/bdraco/home-assistant/homeassistant/core.py", line 576, in async_run_hass_job
    return self.async_add_hass_job(hassjob, *args)
  File "/Users/bdraco/home-assistant/homeassistant/core.py", line 479, in async_add_hass_job
    task = self.loop.create_task(hassjob.target(*args))
Traceback (most recent call last):
  File "/Users/bdraco/home-assistant/venv/lib/python3.10/site-packages/bleak_retry_connector/__init__.py", line 491, in establish_connection
    await client.connect(
  File "/Users/bdraco/home-assistant/homeassistant/components/bluetooth/models.py", line 289, in connect
    self._async_get_backend() or self._async_get_fallback_backend()
  File "/Users/bdraco/home-assistant/homeassistant/components/bluetooth/models.py", line 362, in _async_get_fallback_backend
    raise BleakError(
bleak.exc.BleakError: No backend with an available connection slot that can reach address CA:D5:1A:5B:E3:A9 was found

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/bdraco/home-assistant/venv/lib/python3.10/site-packages/aiohomekit/controller/ble/connection.py", line 47, in establish_connection
    return await retry_establish_connection(
  File "/Users/bdraco/home-assistant/venv/lib/python3.10/site-packages/bleak_retry_connector/__init__.py", line 564, in establish_connection
    _raise_if_needed(name, description, exc)
  File "/Users/bdraco/home-assistant/venv/lib/python3.10/site-packages/bleak_retry_connector/__init__.py", line 442, in _raise_if_needed
    raise BleakConnectionError(msg) from exc
bleak_retry_connector.BleakConnectionError: Eve Motion 41A4 [CA:D5:1A:5B:E3:A9] (id=4B:10:3C:BB:EF:8E) - CA:D5:1A:5B:E3:A9: Failed to connect: No backend with an available connection slot that can reach address CA:D5:1A:5B:E3:A9 was found

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/bdraco/home-assistant/homeassistant/components/homekit_controller/connection.py", line 189, in _async_retry_populate_ble_accessory_state
    await self.pairing.async_populate_accessories_state(force_update=True)
  File "/Users/bdraco/home-assistant/venv/lib/python3.10/site-packages/aiohomekit/controller/ble/pairing.py", line 813, in async_populate_accessories_state
    await self._async_populate_accessories_state(force_update, attempts)
  File "/Users/bdraco/home-assistant/venv/lib/python3.10/site-packages/aiohomekit/controller/ble/pairing.py", line 162, in _async_operation_lock_wrap
    return await func(self, *args, **kwargs)
  File "/Users/bdraco/home-assistant/venv/lib/python3.10/site-packages/bleak_retry_connector/__init__.py", line 600, in _async_wrap_bluetooth_connection_error_retry
    return await func(*args, **kwargs)
  File "/Users/bdraco/home-assistant/venv/lib/python3.10/site-packages/aiohomekit/controller/ble/pairing.py", line 825, in _async_populate_accessories_state
    await self._populate_accessories_and_characteristics(force_update, attempts)
  File "/Users/bdraco/home-assistant/venv/lib/python3.10/site-packages/aiohomekit/controller/ble/pairing.py", line 859, in _populate_accessories_and_characteristics
    await self._ensure_connected(attempts)
  File "/Users/bdraco/home-assistant/venv/lib/python3.10/site-packages/aiohomekit/controller/ble/pairing.py", line 398, in _ensure_connected
    self.client = await establish_connection(
  File "/Users/bdraco/home-assistant/venv/lib/python3.10/site-packages/aiohomekit/controller/ble/connection.py", line 57, in establish_connection
    raise AccessoryDisconnectedError(ex) from ex
aiohomekit.exceptions.AccessoryDisconnectedError: Eve Motion 41A4 [CA:D5:1A:5B:E3:A9] (id=4B:10:3C:BB:EF:8E) - CA:D5:1A:5B:E3:A9: Failed to connect: No backend with an available connection slot that can reach address CA:D5:1A:5B:E3:A9 was found
```