Updated discord.py to 1.3.4
returns error TypeError: __new__() got an unexpected keyword argument 'deny_new' on 1.3.3, updated to 1.3.4 and error no longer occurs