- Fixed traceback AttributeError: 'tuple' object has no attribute 'update' (fixes #8493)   - Introduced ability to debug picture when a face is or not detected.   - Treats exception when image cannot be parsed   - Modified state_attributes to return the face_name attribute instead object