solaredge renamed keys update in sensor.py
It seems my PR #58773 failed to update the relevant keys in sensor.py.

As a consequence the solaredge integration fails to load in 2021.11.0b3.

Which is resolved in this PR. @frenck @terminet85 

Logger: homeassistant.components.sensor
Source: components/solaredge/sensor.py:107
Integration: Sensor (documentation, issues)
First occurred: 5:01:32 PM (4 occurrences)
Last logged: 5:35:14 PM

Error while setting up solaredge platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/src/homeassistant/homeassistant/components/solaredge/sensor.py", line 45, in async_setup_entry
    sensor = sensor_factory.create_sensor(sensor_type)
  File "/usr/src/homeassistant/homeassistant/components/solaredge/sensor.py", line 107, in create_sensor
    sensor_class, service = self.services[sensor_type.key]
KeyError: 'purchased_energy'