Add ability to continue scripts/automations on Connection error exception
now there is only option to continue on error of "HomeAssistantError" , with the Nuki Lock bridge there is a problem when the request is sending to the device and the result can be ConnectionError : 
ConnectionError: Http response for http://XX.XXX.XX.XX:8080/lockAction?token=HXXXXXXXX&action=3&nukiId=XXXXXXX&deviceType=4: 503 Service Unavailable
and the "continue on error" in the automations stop because the error exceptions doesn't allow it
I have added the exceptions of ConnectionError and it worked, please approve