Fix RGB only (no color temp) devices with tplink
Fixes
```
2021-10-07 08:38:37 ERROR (MainThread) [homeassistant.components.light] Error while setting up tplink platform for light
Traceback (most recent call last):
  File "/Users/bdraco/home-assistant/homeassistant/helpers/entity_platform.py", line 257, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/Users/bdraco/home-assistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/Users/bdraco/home-assistant/homeassistant/helpers/entity_platform.py", line 587, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/Users/bdraco/home-assistant/homeassistant/helpers/entity.py", line 682, in add_to_platform_finish
    self.async_write_ha_state()
  File "/Users/bdraco/home-assistant/homeassistant/helpers/entity.py", line 456, in async_write_ha_state
    self._async_write_ha_state()
  File "/Users/bdraco/home-assistant/homeassistant/helpers/entity.py", line 491, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/Users/bdraco/home-assistant/homeassistant/components/light/__init__.py", line 854, in state_attributes
    color_mode = self._light_internal_color_mode
  File "/Users/bdraco/home-assistant/homeassistant/components/light/__init__.py", line 682, in _light_internal_color_mode
    color_mode = self.color_mode
  File "/Users/bdraco/home-assistant/homeassistant/components/tplink/light.py", line 148, in color_mode
    if self.device.color_temp:
  File "/Users/bdraco/home-assistant/venv/lib/python3.9/site-packages/kasa/smartdevice.py", line 87, in wrapped
    return f(*args, **kwargs)
  File "/Users/bdraco/home-assistant/venv/lib/python3.9/site-packages/kasa/smartbulb.py", line 281, in color_temp
    raise SmartDeviceException("Bulb does not support colortemp.")
kasa.exceptions.SmartDeviceException: Bulb does not support colortemp.

```