Fix reload race in shelly when device is offline
Normally this works just fine because we see the device
as not connected in time, but if you happen to be adjusting
wiring, replug in the device, and reload the integration at
the wrong time it ends up in a unrecoverable state.

If shelly reloaded the the RPC device had gone offline before
the lib sees it offline, it would still try to stop the
bluetooth scanner which would fail and than prevent the
integration from reloading without restarting Home Assistant

Fixes
```
2022-12-21 00:20:05.055 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry Garage MyQ Reset for shelly
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aioshelly/rpc_device/device.py", line 275, in call_rpc
    return await self._wsrpc.call(method, params)
  File "/usr/local/lib/python3.10/site-packages/aioshelly/rpc_device/wsrpc.py", line 362, in call
    resp = await self._rpc_call(method, params, timeout)
  File "/usr/local/lib/python3.10/site-packages/aioshelly/rpc_device/wsrpc.py", line 394, in _rpc_call
    resp: dict[str, Any] = await call.resolve
aioshelly.exceptions.DeviceConnectionError: <aioshelly.rpc_device.wsrpc.RPCCall object at 0x7fa0505847f0>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 515, in async_unload
    result = await component.async_unload_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/shelly/__init__.py", line 314, in async_unload_entry
    await shelly_entry_data.rpc.shutdown()
  File "/usr/src/homeassistant/homeassistant/components/shelly/coordinator.py", line 572, in shutdown
    await async_stop_scanner(self.device)
  File "/usr/local/lib/python3.10/site-packages/aioshelly/ble/__init__.py", line 35, in async_stop_scanner
    script_name_to_id = await _async_get_scripts_by_name(device)
  File "/usr/local/lib/python3.10/site-packages/aioshelly/ble/__init__.py", line 29, in _async_get_scripts_by_name
    scripts = await device.script_list()
  File "/usr/local/lib/python3.10/site-packages/aioshelly/rpc_device/device.py", line 218, in script_list
    data = await self.call_rpc("Script.List")
  File "/usr/local/lib/python3.10/site-packages/aioshelly/rpc_device/device.py", line 281, in call_rpc
    raise DeviceConnectionError from err
aioshelly.exceptions.DeviceConnectionError
2022-12-21 00:20:05.256 INFO (MainThread) [aioshelly.rpc_device.wsrpc] Connected to 192.168.106.39      ```