Fix missing exception catch in august to prevent failed setup
Fixes
```
2022-02-07 23:08:55 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry XXXXX august
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/yalexs/api_async.py", line 316, in _raise_response_exceptions
    response.raise_for_status()
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 1004, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 502, message='Bad Gateway', url=URL('https://api-production.august.com/locks/XXXXX’)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 328, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/august/__init__.py", line 43, in async_setup_entry
    return await async_setup_august(hass, entry, august_gateway)
  File "/usr/src/homeassistant/homeassistant/components/august/__init__.py", line 83, in async_setup_august
    await data[DATA_AUGUST].async_setup()
  File "/usr/src/homeassistant/homeassistant/components/august/__init__.py", line 123, in async_setup
    await self._async_refresh_device_detail_by_ids(
  File "/usr/src/homeassistant/homeassistant/components/august/__init__.py", line 219, in _async_refresh_device_detail_by_ids
    await self._async_refresh_device_detail_by_id(device_id)
  File "/usr/src/homeassistant/homeassistant/components/august/__init__.py", line 236, in _async_refresh_device_detail_by_id
    await self._async_update_device_detail(
  File "/usr/src/homeassistant/homeassistant/components/august/__init__.py", line 266, in _async_update_device_detail
    self._device_detail_by_id[device.device_id] = await api_call(
  File "/usr/local/lib/python3.9/site-packages/yalexs/api_async.py", line 115, in async_get_lock_detail
    response = await self._async_dict_to_api(
  File "/usr/local/lib/python3.9/site-packages/yalexs/api_async.py", line 309, in _async_dict_to_api
    _raise_response_exceptions(response)
  File "/usr/local/lib/python3.9/site-packages/yalexs/api_async.py", line 330, in _raise_response_exceptions
    raise AugustApiAIOHTTPError(
yalexs.exceptions.AugustApiAIOHTTPError: The operation failed with error code 502: Bad Gateway.
```