Fix HKC device triggers
The callback can be any type as we assumed it was always a task

```
022-07-17 12:34:14.228 ERROR (MainThread) [aiohomekit.utils] Failure running background task: Task-13090
Traceback (most recent call last):
  File "/Users/bdraco/home-assistant/venv/lib/python3.10/site-packages/aiohomekit/utils.py", line 28, in _handle_task_result
    task.result()
  File "/Users/bdraco/home-assistant/venv/lib/python3.10/site-packages/aiohomekit/controller/ble/pairing.py", line 312, in _async_callback
    listener(results)
  File "/Users/bdraco/home-assistant/homeassistant/components/homekit_controller/connection.py", line 615, in process_new_events
    async_fire_triggers(self, new_values_dict)
  File "/Users/bdraco/home-assistant/homeassistant/components/homekit_controller/device_trigger.py", line 244, in async_fire_triggers
    source = trigger_sources[device_id]
  File "/Users/bdraco/home-assistant/homeassistant/components/homekit_controller/device_trigger.py", line 78, in fire
    event_handler(value)
  File "/Users/bdraco/home-assistant/homeassistant/components/homekit_controller/device_trigger.py", line 96, in event_handler
    self._hass.async_create_task(
  File "/Users/bdraco/home-assistant/homeassistant/core.py", line 484, in async_create_task
    task = self.loop.create_task(target)
  File "/opt/homebrew/Cellar/python@3.10/3.10.5/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 438, in create_task
    task = tasks.Task(coro, loop=self, name=name)
TypeError: a coroutine was expected, got None```