Set isolated_build = True for tox
Fixes this error when running tests locally:
ERROR: pyproject.toml file found.
To use a PEP 517 build-backend you are required to configure tox to
use an isolated_build:
https://tox.readthedocs.io/en/latest/example/package.html