Bump pycups to 2.0.4
pycups 1.9.73 does not work on Python 3.13 because
it calls `PyEval_CallObject` which no longer exists.
2.0.3 changed the call to `PyObject_Call`

https://docs.python.org/3/whatsnew/3.13.html

ImportError: Error relocating /usr/local/lib/python3.13/site-packages/cups.cpython-313-x86_64-linux-musl.so: PyEval_CallObject: symbol not found