Avoid divide by zero errors in pyHS100
Some bulbs such as kl125 don't have a definition submitted into
pyHS100.  Trying to interact with them will cause a divide by
zero error:
```
  File "/usr/src/homeassistant/homeassistant/components/tplink/light.py", line 248, in attempt_update
    self._light_features = self._get_light_features()
  File "/usr/src/homeassistant/homeassistant/components/tplink/light.py", line 289, in _get_light_features
    min_mireds = kelvin_to_mired(min_range)
  File "/usr/src/homeassistant/homeassistant/util/color.py", line 515, in color_temperature_kelvin_to_mired
    return math.floor(1000000 / kelvin_temperature)
ZeroDivisionError: division by zero
```

As the `pyHS100` project has been abandoned in favor of `python-kasa` but there isn't yet
a component in home assistant for using `python-kasa` move the bulb definitions into this file and
add some fallback code into the component.

If the light specifies it supports color temperature but the range isn't available choose a "safe"
range that is the minimum of what is available in bulbs today.