Fix KeyError when triggering an alarm that is already triggered
_trigger_time_by_state doesn't have a value for 'triggered' so calling
alarm_trigger while self._active_state is 'triggered' resulted in the
following exception being raised:

```
2019-09-10 21:11:32 ERROR (MainThread) [homeassistant.components.automation] Error while executing automation automation.automation_name. Unknown error for call_service at pos 2:
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/homeassistant/components/automation/__init__.py", line 431, in action
    await script_obj.async_run(variables, context)
  File "/usr/lib/python3.7/site-packages/homeassistant/helpers/script.py", line 151, in async_run
    await self._handle_action(action, variables, context)
  File "/usr/lib/python3.7/site-packages/homeassistant/helpers/script.py", line 235, in _handle_action
    await self._actions[_determine_action(action)](action, variables, context)
  File "/usr/lib/python3.7/site-packages/homeassistant/helpers/script.py", line 318, in _async_call_service
    context=context,
  File "/usr/lib/python3.7/site-packages/homeassistant/helpers/service.py", line 98, in async_call_from_config
    domain, service_name, service_data, blocking=blocking, context=context
  File "/usr/lib/python3.7/site-packages/homeassistant/core.py", line 1235, in async_call
    await asyncio.shield(self._execute_service(handler, service_call))
  File "/usr/lib/python3.7/site-packages/homeassistant/core.py", line 1260, in _execute_service
    await handler.func(service_call)
  File "/usr/lib/python3.7/site-packages/homeassistant/helpers/entity_component.py", line 210, in handle_service
    self._platforms.values(), func, call, service_name, required_features
  File "/usr/lib/python3.7/site-packages/homeassistant/helpers/service.py", line 349, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/lib/python3.7/site-packages/homeassistant/helpers/service.py", line 371, in _handle_service_platform_call
    await getattr(entity, func)(**data)
  File "/usr/lib64/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.7/site-packages/homeassistant/components/manual/alarm_control_panel.py", line 321, in alarm_trigger
    if not self._trigger_time_by_state[self._active_state]:
KeyError: 'triggered'
```

In that case, just ignore the call to alarm_trigger since it wouldn't do
anything anyway.