Fix dumping lru stats in the profiler
DomainData no longer has an LRU

```
  File "/usr/src/homeassistant/homeassistant/components/profiler/__init__.py", line 202, in _lru_stats
    for maybe_lru in class_with_lru_attr.__dict__.values():
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DomainData' object has no attribute '__dict__'
```