Add missing exception handlers to radiotherm
After upgrading access point firmware and restarting HA,
radiotherm failed to setup due to the following exceptions:

```
Traceback (most recent call last):
....
  File "/usr/local/lib/python3.9/socket.py", line 832, in create_connection
    sock.connect(sa)
OSError: [Errno 113] Host is unreachable

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 339, in async_setup
    result = await component.async_setup_entry(hass, self)
...
  File "/usr/local/lib/python3.9/urllib/request.py", line 1349, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 113] Host is unreachable>
```

This PR adds exception catches for these to ensure config entry
setup is retried later when the network is available again