Update requirements.txt
Consider changing aiohttp==3.8.3 (from aiohttp==3.8.1), 3.81 makes error on Python 3.11.2.
When I changed to 3.8.3 my installation on Sony Xperia X with Ubuntu Touch and newes Python, SQLite, OpenSSL went succesfully.

with aiohttp==3.8.1:

Building wheels for collected packages: aiohttp, ciso8601, home-assistant-bluetooth, yarl
  Building wheel for aiohttp (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for aiohttp (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [105 lines of output]
      *********************
      * Accelerated build *
      *********************
      running bdist_wheel
      running build
(...)
      building 'aiohttp._websocket' extension
      creating build/temp.linux-aarch64-cpython-311
      creating build/temp.linux-aarch64-cpython-311/aiohttp
      gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/homeassistant/include -I/usr/local/include/python3.11 -c aiohttp/_websocket.c -o build/temp.linux-aarch64-cpython-311/aiohttp/_websocket.o
      aiohttp/_websocket.c:198:27: fatal error: longintrepr.h: No such file or directory
      compilation terminated.
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for aiohttp

  
  
===================

changed to aiohttp==3.8.3
  
  (homeassistant) root@ubuntu-phablet:/homeassistant# python3.11 -m pip install /root/tmp/core-2023.2.4
Processing /root/tmp/core-2023.2.4
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting aiohttp==3.8.3

(...)
Stored in directory: /home/phablet/.cache/pip/wheels/95/82/db/c48e0a572594c30fc0079e13d3bb06b99b78e880045d3438c6
Successfully built homeassistant
Installing collected packages: 
(...)
  Running setup.py install for python-slugify ... done
(Successfully installed MarkupSafe-2.1.2 PyJWT-2.5.0 aiohttp-3.8.3 aiosignal-1.3.1 anyio-3.6.2 astral-2.2 async-timeout-4.0.2 atomicwrites-homeassistant-1.4.1 attrs-22.2.0 awesomeversion-22.9.0 bcrypt-4.0.1 certifi-2022.12.7 cffi-1.15.1 charset-normalizer-2.1.1 ciso8601-2.3.0 cryptography-39.0.1 frozenlist-1.3.3 h11-0.14.0 home-assistant-bluetooth-1.9.2 homeassistant-2023.2.4 httpcore-0.16.3 httpx-0.23.3 idna-3.4 ifaddr-0.1.7 jinja2-3.1.2 lru-dict-1.1.8 multidict-6.0.4 orjson-3.8.5 pyOpenSSL-23.0.0 pycparser-2.21 python-slugify-4.0.1 pytz-2022.7.1 pyyaml-6.0 requests-2.28.1 rfc3986-1.5.0 sniffio-1.3.0 text-unidecode-1.3 typing-extensions-4.4.0 urllib3-1.26.14 voluptuous-0.13.1 voluptuous-serialize-2.5.0 yarl-1.8.1


my setup:

root@ubuntu-phablet:/# python3 --version
Python 3.11.2
root@ubuntu-phablet:/# sqlite3 --version
3.40.1 2022-12-28 14:03:47 df5c253c0b3dd24916e4ec7cf77d3db5294cc9fd45ae7b9c5e82ad8197f38a24
root@ubuntu-phablet:/# openssl version
OpenSSL 3.0.8 7 Feb 2023 (Library: OpenSSL 3.0.8 7 Feb 2023)
root@ubuntu-phablet:/#

root@ubuntu-phablet:~# cat /etc/issue
Ubuntu 16.04.7 LTS \n \l

root@ubuntu-phablet:~# cat /proc/cpuinfo |grep -E 'Processor|Hardware'
Processor	: AArch64 Processor rev 4 (aarch64)
Hardware	: Qualcomm Technologies, Inc MSM8956